# IMPORTING LIBRARIES AND DATA
```{r setup, include=FALSE}
#importing libraries
library(readr)
library(dplyr)
library(tree)
library(ISLR)
library(randomForest)
library(e1071)

#data import
cleveland <- read.csv(file="processed.cleveland.csv", header = TRUE , sep = "", na.strings = "?")
hungary <- read.csv(file="processed.hungarian.csv", header = TRUE , sep = "", na.strings = "?")
swiss <- read.csv(file="processed.switzerland.csv", header = TRUE , sep = ",", na.strings = "?")
va <- read.csv(file="processed.va.csv", header = TRUE , sep = ",", na.strings = "?")
```

# PREPROCESS DATA - STAGE 1
##PREPROCESS AND REPLACE MISSING VALUES
```{r}
for(i in 1:ncol(cleveland))
{
  cleveland[is.na(cleveland[,i]), i] <- median(cleveland[,i], na.rm = TRUE)
}

for(i in 1:ncol(hungary))
{
  hungary[is.na(hungary[,i]), i] <- median(hungary[,i], na.rm = TRUE)
}

for(i in 1:ncol(swiss))
{
  swiss[is.na(swiss[,i]), i] <- median(swiss[,i], na.rm = TRUE)
}

for(i in 1:ncol(va))
{
  va[is.na(va[,i]), i] <- median(va[,i], na.rm = TRUE)
}
```


# MERGING ALL 4 DATASETS
```{r}
df <- dplyr::bind_rows(cleveland %>% rename(class = num) %>% mutate(country = "Cleveland"),
                        hungary %>% mutate(country = "Hungary"),
                        swiss %>% mutate(country = "Switzerland"))
```

# PREPROCESS DATA - STAGE 2
```{r}
##CONVERT CONTINUOUS TO CATEGORICAL 
breaks <- c(0,30, 35, 40, 50, 60, 70, 80, 90, 100, Inf)
age_transformed <- cut(df$age,breaks = breaks, right=FALSE, labels=c(1:10))
breaks1 <- c(0, 110, 120, 130, 140, 150, 160, Inf)
trestbps_transformed <-cut(df$trestbps,breaks = breaks1, right=FALSE, labels=c(1:7))
breaks2 <- c(0, 180, 200, 220, 240, 260, 280, 300, Inf)
chol_transformed <-cut(df$chol,breaks = breaks2, right=FALSE, labels=c(1:8))
breaks3 <- c(0, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, Inf)
thalach_transformed <-cut(df$thalach,breaks = breaks3, right=FALSE, labels=c(1:13))
breaks4 <- c(-10, 0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, Inf)
oldpeak_transformed <- cut(df$oldpeak,breaks = breaks4, right=FALSE, labels=c(1:14))

##REPLACE DATA WITH NEW TRANSFORMED VALUES
for(i in 1:ncol(df))
{
  df$age <- age_transformed
  df$trestbps <- trestbps_transformed
  df$chol <- chol_transformed
  df$thalach <- thalach_transformed
  df$oldpeak <- oldpeak_transformed
}
```

# CHANGE BINARY VARIABLES TO FACTORS
```{r}
df <- df %>% mutate(num = if_else(df$class> 0, 1, 0),
                    age = as.factor(.$age),
                    sex = as.factor(.$sex),
                    cp = as.factor(.$cp),
                    trestbps = as.factor(.$trestbps),
                    chol = as.factor(.$chol),
                    fbs = as.factor(.$fbs),
                    restecg = as.factor(.$restecg),
                    thalach = as.factor(.$thalach),
                    exang = as.factor(.$exang),
                    oldpeak = as.factor(.$oldpeak),
                    slope = as.factor(.$slope),
                    ca = as.factor(.$ca),
                    thal = as.factor(.$thal),
                    class = as.factor(.$class),
                    country = as.factor(.$country))

df$num = as.factor(df$num)

levels(df$num) <- c("No disease","Disease")

##REMOVING UNWANTED ATTRIBUTES
df1 = subset(df, select = -c(6, 15)) 
## CLASS 
table(df1$num)
df1$class <- NULL
```

# DIVIDE TRAINING AND TESTING DATA SETS
```{r}
library(caret)
set.seed(527)
train_rows <- caret::createDataPartition(df$num,p=0.7,list=FALSE)
train_data <- df1[train_rows,]
test_data <-  df1[-train_rows,]
```

# LOGISTIC REGRESSION
```{r}
library(nnet)
# Fit the model
glm_fit <- nnet::multinom(train_data$num ~ ., data=train_data)
input_data <- test_data[2, ] %>% select(-num)
pred <- predict(glm_fit, input_data)
pred
```

```{r}
save(glm_fit , file = 'logreg.rda')
```

